### ISSUE TITLE
Expose an error type

### ISSUE THREAD

**Issue by juh9870** [mthh/contour-rs#9]
Currently, methods return an error type, which is impossible to access from other crates, and so it is impossible to make any reasonable error handling beyond "something gone wrong".

`Error` struct is public, but `error` module is not, and it is not re-exported, so we can't name this type in a code and can't match on its kind,

**Comment by mthh** [comment]
Thanks for your report!
I will expose publicly `Error` struct and `ErrorKind` enum.
